from dataclasses import dataclass

@dataclass
class MapConfig:
    MAP_FILE_NAME: str
    MAP_WIDTH_CM: float
    MAP_HEIGHT_CM: float
    MAP_MARGIN_CM: float
    MAP_CM_PER_PIXELS: float
    
    ROBOT_INIT_POS_X_CM: float
    ROBOT_INIT_POS_Y_CM: float
    ROBOT_INIT_ANGLE: float
    
    MIN_LEFT_MARKER_COUNTER: int


map_raiju = MapConfig(
    MAP_FILE_NAME = "map-raiju.png",
    MAP_WIDTH_CM = 96.0,
    MAP_HEIGHT_CM = 301.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 3.0,
    ROBOT_INIT_POS_X_CM = 11.0,
    ROBOT_INIT_POS_Y_CM = 200.0,
    ROBOT_INIT_ANGLE = 90.0,
    MIN_LEFT_MARKER_COUNTER = 20,
)

rsm_2022 = MapConfig(
    MAP_FILE_NAME = "rsm-2022.png",
    MAP_WIDTH_CM = 186.0,
    MAP_HEIGHT_CM = 354.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 2.0,
    ROBOT_INIT_POS_X_CM = 178.0,
    ROBOT_INIT_POS_Y_CM = 75.0,
    ROBOT_INIT_ANGLE = 270.0,
    MIN_LEFT_MARKER_COUNTER = 26,
)

rsm_2023 = MapConfig(
    MAP_FILE_NAME = "rsm-2023.png",
    MAP_WIDTH_CM = 230.0,
    MAP_HEIGHT_CM = 395.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 2.0,
    ROBOT_INIT_POS_X_CM = 11.0,
    ROBOT_INIT_POS_Y_CM = 125.0,
    ROBOT_INIT_ANGLE = 90.0,
    MIN_LEFT_MARKER_COUNTER = 20,
)

rc_2023 = MapConfig(
    MAP_FILE_NAME = "rc-2023.png",
    MAP_WIDTH_CM = 545.0,
    MAP_HEIGHT_CM = 595.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 1.5,
    ROBOT_INIT_POS_X_CM = 220.0,
    ROBOT_INIT_POS_Y_CM = 12.0,
    ROBOT_INIT_ANGLE = 180.0,
    MIN_LEFT_MARKER_COUNTER = 40,
)

rc_2025 = MapConfig(
    MAP_FILE_NAME = "rc-2025.png",
    MAP_WIDTH_CM = 360.0,
    MAP_HEIGHT_CM = 330.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 2.2,
    ROBOT_INIT_POS_X_CM = 11.0,
    ROBOT_INIT_POS_Y_CM = 210.0,
    ROBOT_INIT_ANGLE = 90.0,
    MIN_LEFT_MARKER_COUNTER = 50,
)

all_japan_2018 = MapConfig(
    MAP_FILE_NAME = "all-japan-2018.png",
    MAP_WIDTH_CM = 665.0,
    MAP_HEIGHT_CM = 309.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 2.0,
    ROBOT_INIT_POS_X_CM = 5.0,
    ROBOT_INIT_POS_Y_CM = 165.0,
    ROBOT_INIT_ANGLE = 90.0,
    MIN_LEFT_MARKER_COUNTER = 60,
)

all_japan_2019 = MapConfig(
    MAP_FILE_NAME = "all-japan-2019.png",
    MAP_WIDTH_CM = 688.0,
    MAP_HEIGHT_CM = 430.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 2.0,
    ROBOT_INIT_POS_X_CM = 675.0,
    ROBOT_INIT_POS_Y_CM = 325.0,
    ROBOT_INIT_ANGLE = 90.0,
    MIN_LEFT_MARKER_COUNTER = 60,
)

all_japan_2020 = MapConfig(
    MAP_FILE_NAME = "all-japan-2020.png",
    MAP_WIDTH_CM = 303.0,
    MAP_HEIGHT_CM = 227.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 3.0,
    ROBOT_INIT_POS_X_CM = 9.0,
    ROBOT_INIT_POS_Y_CM = 135.0,
    ROBOT_INIT_ANGLE = 90.0,
    MIN_LEFT_MARKER_COUNTER = 40,
)


all_japan_2021 = MapConfig(
    MAP_FILE_NAME = "all-japan-2021.png",
    MAP_WIDTH_CM = 600.0,
    MAP_HEIGHT_CM = 378.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 2.0,
    ROBOT_INIT_POS_X_CM = 9.0,
    ROBOT_INIT_POS_Y_CM = 155.0,
    ROBOT_INIT_ANGLE = 90.0,
    MIN_LEFT_MARKER_COUNTER = 58,
)

all_japan_2022 = MapConfig(
    MAP_FILE_NAME = "all-japan-2022.png",
    MAP_WIDTH_CM = 651.0,
    MAP_HEIGHT_CM = 317.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 2.0,
    ROBOT_INIT_POS_X_CM = 125.0,
    ROBOT_INIT_POS_Y_CM = 308.0,
    ROBOT_INIT_ANGLE = 180.0,
    MIN_LEFT_MARKER_COUNTER = 33,
)

all_japan_2023 = MapConfig(
    MAP_FILE_NAME = "all-japan-2023.png",
    MAP_WIDTH_CM = 620.0,
    MAP_HEIGHT_CM = 312.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 2.0,
    ROBOT_INIT_POS_X_CM = 80.0,
    ROBOT_INIT_POS_Y_CM = 300.0,
    ROBOT_INIT_ANGLE = 0.0,
    MIN_LEFT_MARKER_COUNTER = 1,
)


all_japan_2024 = MapConfig(
    MAP_FILE_NAME = "all-japan-2024.png",
    MAP_WIDTH_CM = 829.0,
    MAP_HEIGHT_CM = 304.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 2.0,
    ROBOT_INIT_POS_X_CM = 433.0,
    ROBOT_INIT_POS_Y_CM = 11.0,
    ROBOT_INIT_ANGLE = 0.0,
    MIN_LEFT_MARKER_COUNTER = 5,
)

copa_pinhao_2024 = MapConfig(
    MAP_FILE_NAME = "copa-pinhao-2024.png",
    MAP_WIDTH_CM = 405.0,
    MAP_HEIGHT_CM = 132.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 3.0,
    ROBOT_INIT_POS_X_CM = 195.0,
    ROBOT_INIT_POS_Y_CM = 20.0,
    ROBOT_INIT_ANGLE = 180.0,
    MIN_LEFT_MARKER_COUNTER = 40,
)

map_rcx_2024 = MapConfig(
    MAP_FILE_NAME = "rcx-2024.png",
    MAP_WIDTH_CM = 653.0,
    MAP_HEIGHT_CM = 255.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 2.0,
    ROBOT_INIT_POS_X_CM = 640.0,
    ROBOT_INIT_POS_Y_CM = 100.0,
    ROBOT_INIT_ANGLE = 90.0,
    MIN_LEFT_MARKER_COUNTER = 53,
)


iron_cup_2026 = MapConfig(
    MAP_FILE_NAME = "ironcup-2026.png",
    MAP_WIDTH_CM = 534.0,
    MAP_HEIGHT_CM = 345.0,
    MAP_MARGIN_CM = 25.0,
    MAP_CM_PER_PIXELS = 2.0,
    ROBOT_INIT_POS_X_CM = 12.0,
    ROBOT_INIT_POS_Y_CM = 250.0,
    ROBOT_INIT_ANGLE = 270.0,
    MIN_LEFT_MARKER_COUNTER = 50,
)